### ISSUE TITLE
Upgrade caddy from 2.4.0 to 2.5.0 (Security Update)

### ISSUE THREAD

**Issue by CL0Pinette** [caddy-dns/netlify#1]

**Comment by mholt** [comment]
Fwiw, these alerts are false positives. You can ignore them (sigh).

Still doesn't hurt to upgrade. 🤷‍♂️ But absolutely nothing in the alert has any effect on any module as far as I know.

**Comment by CL0Pinette** [comment]
Alright, I saw the warning and was like "Damn gotta fix this" haha, I'll close this.
